// Author: Ian D. Hanley @ KMicro Tech Inc. | LinkedIn: https://www.linkedin.com/company/kmicro/ | Blog: https://kmicro.com/blog/
// Ever wonder how many times each account in your environment throws a specific EventID per day?

SecurityEvent                     // <--Define the table to query
| where EventID == "4662"         // <--Declare which EventID you're looking for
| summarize count() by Account    // <--Show how many times that EventID was thrown per account
| render columnchart              // <--Optional, but helps quickly visualize potential outliers
